In [1]:
#Q1 A
import numpy as np
foo=np.arange(0,30)
print("foo: ",foo)
print("shape of foo is: ",foo.shape)

foo:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
shape of foo is:  (30,)


In [2]:
#B
bar=foo.reshape(2,-1)
print(bar)
print("shape of bar: ",bar.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
shape of bar:  (2, 15)


In [3]:
#C
baz=foo.reshape(3,2,-1)
print(baz)
print("shape of bar: ",baz.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
shape of bar:  (3, 2, 5)


In [4]:
#D
bar[1][0]=-1
print("bar: ", bar)
print("baz: ", baz)
print("foo: ", foo)

'''NumPy's reshape function provides a new view of the original array's data, not creating a physical copy in memory. 
Thus changing bar changed foo and bazas well'''

bar:  [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [-1 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
baz:  [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [-1 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
foo:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 -1 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


"NumPy's reshape function provides a new view of the original array's data, not creating a physical copy in memory. \nThus changing bar changed foo and bazas well"

In [5]:
#E
print("sum over 2nd dimension: ",baz.sum(axis=2))
print("sum over 3rd dimension: ",baz.sum(axis=1))
c=baz.sum(axis=0)
print("sum over 1st dimension: ",c)
print("sum over 3rd dimension: ",c.sum(axis=0))


sum over 2nd dimension:  [[ 10  35]
 [ 60  69]
 [110 135]]
sum over 3rd dimension:  [[ 5  7  9 11 13]
 [ 9 27 29 31 33]
 [45 47 49 51 53]]
sum over 1st dimension:  [[30 33 36 39 42]
 [29 48 51 54 57]]
sum over 3rd dimension:  [59 81 87 93 99]


In [6]:
#F
print("2nd row of bar: ",bar[1,:])
print("last col of bar: ",bar[:,-1])
print("top right 2x2 submatrix of bar: ",bar[:,-2:15])


2nd row of bar:  [-1 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
last col of bar:  [14 29]
top right 2x2 submatrix of bar:  [[13 14]
 [28 29]]


In [7]:
#Q2 A
print(np.arange(10)+1)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
#B 
a=np.arange(10)+2
b=a.copy()
for i in range(1,10):
    b=np.append(b,a+i)
print(b.reshape(10,10))
    
        

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [9]:
#C
import numpy.random as npr
data=np.exp(npr.randn(50,5))
print(data)

[[ 0.50123586  0.48359386  0.72853528 22.88724312  1.25223387]
 [ 0.35176019  0.43061354  0.36238378  1.87243504  0.21358935]
 [ 0.69022481  4.94352186  0.39054684  1.04327082  0.54337876]
 [ 0.37010852  2.63602536  1.36653423  0.24878292  1.55246453]
 [ 0.40757871  0.3163112   0.19502083  1.00677264 13.50327109]
 [ 1.49864212  0.42995724  0.79190351  0.23606221  0.10804967]
 [ 6.35336819  0.96778335  1.42574405  1.54538167  6.09373883]
 [ 2.81228696  2.68009687  0.29857105  0.45821223  0.45541527]
 [ 0.9419448   1.22519342  1.17440504  0.40220542  0.19563257]
 [ 3.58164119  2.58058787  6.40867899  0.67320326  0.8537608 ]
 [ 2.25842783  0.5645004   0.16892242  0.22212412  0.37260517]
 [ 0.28160725  1.08916696  8.80188286  0.62599261  0.81390384]
 [ 0.42346578  4.17196068  2.48720263  3.19972396  1.0810169 ]
 [ 1.01641247  1.92762267  0.46864295  0.77591683  0.16369544]
 [ 1.45756411  2.47722815  0.37873919  4.64687419  0.77528676]
 [ 0.22864137  1.02356845  0.95165647  0.3597182   0.28

In [10]:
#D
m=np.mean(data,axis=0)
print("mean of each column: ",m)
s=np.std(data,axis=0)
print("standard deviation of each column: ",s)

mean of each column:  [1.32037297 1.74069109 1.74726868 1.64821696 1.51829767]
standard deviation of each column:  [1.26915312 1.54011804 1.75807058 3.1976699  2.21511482]


In [11]:
#E
data=data-m
data=data/s
print(np.mean(data,axis=0))
print(np.std(data,axis=0))

[-5.27355937e-17  1.19904087e-16 -2.59237076e-16  1.40998324e-16
 -5.88418203e-17]
[1. 1. 1. 1. 1.]


In [26]:
def isPrime(n):
    s=int(np.sqrt(n))+1
    prime=True
    for i in range(2,s):
        if n%i==0:
            prime=False
            break
    if prime:
        return n

n = int(input("Enter a number: "))
print(isPrime(n))

print()

print("Prime numbers less than 500")
print([isPrime(i) for i in range(1,500) if isPrime(i)!=None])


Enter a number: 45
None

Prime numbers less than 500
[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499]


In [28]:
#Q4
import pandas as pd
import numpy as np 

data = pd.DataFrame({'group':['a', 'A', 'a', 'b','b', 'B', 'c', 'C','c','c'],'ounces':[4,
3, 12, 6, 7.5, 8, 3, 5, 6,np.NaN]})


data


group  ounces
0     a     4.0
1     A     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     B     8.0
6     c     3.0
7     C     5.0
8     c     6.0
9     c     NaN

In [29]:
#a
data.describe()


ounces
count   9.000000
mean    6.055556
std     2.855307
min     3.000000
25%     4.000000
50%     6.000000
75%     7.500000
max    12.000000

In [30]:
#b
'''The info() method prints information about the DataFrame. 
The information contains the number of columns, column labels, column data types, memory usage, range index, and the number of cells in 
each column (non-null values).Note: the info() method actually prints the info.'''
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   group   10 non-null     object 
 1   ounces  9 non-null      float64
dtypes: float64(1), object(1)
memory usage: 292.0+ bytes


In [31]:
#c) sort the data frame by ‘ounces’ - inplace = True

''' The inplace=True parameter is a boolean parameter that is used to modify the original data frame in place. 
By default, the DataFrame.sort_values() function returns a new data frame with the specified columns sorted.'''

data.sort_values(by='ounces',inplace=True)
data

group  ounces
1     A     3.0
6     c     3.0
0     a     4.0
7     C     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     B     8.0
2     a    12.0
9     c     NaN

In [32]:
#d) sort the data frame by ‘group’ in descending order and then by ‘ounces’ in ascending order inplace=False

data.sort_values(by=['group','ounces'],ascending=[False,True],inplace=False)

group  ounces
6     c     3.0
8     c     6.0
9     c     NaN
3     b     6.0
4     b     7.5
0     a     4.0
2     a    12.0
7     C     5.0
5     B     8.0
1     A     3.0

In [33]:
#e) fetch all the duplicated rows if any

''' data.duplicated() - returns boolean value based on all columns(i.e rows where all the column values are same).'''

data[data.duplicated()]


Empty DataFrame
Columns: [group, ounces]
Index: []

In [34]:
#f) drop all the duplicate rows
''' Pandas drop_duplicates() function removes duplicate rows from the DataFrame '''

data.drop_duplicates()

group  ounces
1     A     3.0
6     c     3.0
0     a     4.0
7     C     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     B     8.0
2     a    12.0
9     c     NaN

In [35]:
#g) convert all group letters to lowercase letters

''' The apply() method applies a function along an axis of the dataframe'''

data['group'].apply(lambda x: x.lower())

1    a
6    c
0    a
7    c
3    b
8    c
4    b
5    b
2    a
9    c
Name: group, dtype: object

In [36]:
#h) compute the average ounces for all unique letters

'''groupby() - Pandas groupby is used for grouping the data according to the categories and applying a function to the categories'''

data.groupby(['group']).mean()


ounces
group        
A        3.00
B        8.00
C        5.00
a        8.00
b        6.75
c        4.50

In [37]:
#i) compute value counts where ounces >5
print(data[data.ounces>5])

print("\n\n")

print("Number of ounces > 5:  ", data[data.ounces>5]['ounces'].count())

print("\n\n")

print('value counts where ounces > 5: ')
data[data.ounces>5].groupby(['ounces']).count()



  group  ounces
3     b     6.0
8     c     6.0
4     b     7.5
5     B     8.0
2     a    12.0



Number of ounces > 5:   5



value counts where ounces > 5: 


group
ounces       
6.0         2
7.5         1
8.0         1
12.0        1

In [38]:
#j) compute the cumulative sum of ounces for all rows

data['ounces'].cumsum()

1     3.0
6     6.0
0    10.0
7    15.0
3    21.0
8    27.0
4    34.5
5    42.5
2    54.5
9     NaN
Name: ounces, dtype: float64

In [39]:
#k) data.shape[0]

''' data.shape - shape of the table - 10X2 '''

data.shape[0]


10

In [40]:
#l) data.shape[0] -data.dropna()- shape[0]
''' The dropna() method removes the rows that contains NULL values.'''
 
x=data.dropna()

print("No. of Null value rows dropped : ")
data.shape[0] - x.shape[0]




No. of Null value rows dropped : 


1

In [41]:
#m) isnull()
'''The isnull() method returns a DataFrame object where all the values are replaced with a Boolean value True for NULL values, and otherwise False.'''

''' In summary, isna() and isnull() are two Pandas functions that are used to identify missing values in a DataFrame. 
They are essentially the same function, except that isnull() is a method of Pandas Series objects,while isna() is a method of 
both Series and DataFrame objects.'''


data.isnull()

group  ounces
1  False   False
6  False   False
0  False   False
7  False   False
3  False   False
8  False   False
4  False   False
5  False   False
2  False   False
9  False    True

In [42]:
#n) unique

'''The unique function in pandas is used to find the unique values in pandas Series'''

print(data['group'].unique())
print(data['ounces'].unique())

['A' 'c' 'a' 'C' 'b' 'B']
[ 3.   4.   5.   6.   7.5  8.  12.   nan]
