In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
df = pd.read_csv(r"C:\Users\HARSHITA\Downloads\Fin.csv")

In [3]:
df.dropna(inplace=True)

In [4]:
X = df.loc[:,["FinScore","LoanAmount"]]
y = df.loc[:,'InterestRate']

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
model = LinearRegression()

In [9]:
model.fit(X_train,y_train)

LinearRegression()

In [10]:
y_pred = model.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r2  = r2_score(y_test,y_pred)

In [12]:
r2

-0.0007689395491616846

Question2

In [13]:
from sklearn import datasets

In [14]:
iris = datasets.load_iris()

In [15]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [16]:
X = iris.data[:,[0,1,2,3]]

In [17]:
y = iris.target

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [20]:
from sklearn.linear_model import LogisticRegression 

In [21]:
model1 = LogisticRegression()

In [22]:
model1.fit(X_train,y_train)

C:\Users\HARSHITA\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [32]:
y_pred = model1.predict(X_test)

In [ ]:
y_cap = model1.predict(X_train)

In [24]:
from sklearn.metrics import classification_report

In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.91      0.95        11
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [26]:
from sklearn.tree import DecisionTreeClassifier
model2 = DecisionTreeClassifier()

In [27]:
model2.fit(X_train,y_train)

DecisionTreeClassifier()

In [28]:
y_pred1 = model2.predict(X_test)

In [29]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.91      0.95        11
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
print(confusion_matrix(y_test,y_pred1))

[[ 8  0  0]
 [ 0 10  1]
 [ 0  0 11]]
