In [6]:
a=10
print('Value of a is : ',a)

Value of a is :  10


In [9]:
a=10
b=10+2j
print(type(a))
type(b)

<class 'int'>


complex

In [10]:
x='10'
print(x)
print(type(x))
x=int(x)
type(x)

10
<class 'str'>


int

In [11]:
a = int(input("Enter the First no. : "))
b = int(input("Enter the Second no. : "))
print("Sum of 2 nos.: ", a+b)
print("Difference of 2 nos.: ", a-b)
print("Product of 2 nos.: ", a*b)
print("Division of 2 nos.: ", a/b)
print("num1 to the power num 2 .: ", a**b)

Enter the First no. : 10
Enter the Second no. : 5
Sum of 2 nos.:  15
Difference of 2 nos.:  5
Product of 2 nos.:  50
Division of 2 nos.:  2.0
num1 to the power num 2 .:  100000


In [12]:
# Result (Marking)

marks= int( input())
if marks>=91:
    print("o")
elif marks>=81:
    print("A+")
elif marks>=71:
    print("A")
elif marks>=61:
    print("B+")
elif marks>=51:
    print("B")
elif marks>=41:
    print("C")
else:
    print("F")
print("EOP")


71
A
EOP


In [22]:
# Identifying Leap Year

year=int(input())
if(year%4==0 and year%100!=0) or (year%400==0):
    print( year,"is a leap year")
else:
    print(year ," is a not leap year")
    

1900
1900  is a not leap year


In [16]:
# Generating Electricity Bill

a = int (input("Enter the unit used "))
if a>100:
    if a>200:
        if a>300:
            if a>400:
                t=(a-400)*10+ 100*4 + 100*2.5 + 100*1.5 + (100*0.5)
            else:
                t=(a%100)*4 + 100*2.5 + 100*1.5 + 100*0.5
        else:
            t=(a%100)*2.5 + 100*1.5 + 100*0.5
    else:
        t=(a%100)*1.5 + 100*0.5
else:
    t=a*0.5

print(t ,"is your electricity bill.")

Enter the unit used 900
5850.0 is your electricity bill.


In [23]:
# Greatest of Three numbers

a=input()
b=input()
c=input()

if a>b:
    if a>c:
        print(a,"is the largest no.")
    else:
        print(c,"is the largest no.")
else:
    if b>c:
        print(b,"is the largest no.")
    else:
        print(c,"is the largest no.")


45
54
98
98 is the largest no.


In [1]:
# Knowing Loops

i=1
while i<11:
    print("This is python class")
    i +=1



This is python class
This is python class
This is python class
This is python class
This is python class
This is python class
This is python class
This is python class
This is python class
This is python class


In [3]:
# Table of no.

num = int(input())
for i in range(1,11):
    print(num,"*",i,"=",i*num)
    

4
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40


In [5]:
# Sum of Digits

a=int(input())
sum=0
while a>0:
    sum +=a%10
    a //=10
print(sum)

538
16


In [1]:
# Print even nos.

for i in range(0,25,2):
    print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24


In [2]:
# continue implementation in for loop

print("printing nos.")
for i in range(1,25):
    if i%3==0:
        print ("skipping the no.")
        continue
    print(i)

printing nos.
1
2
skipping the no.
4
5
skipping the no.
7
8
skipping the no.
10
11
skipping the no.
13
14
skipping the no.
16
17
skipping the no.
19
20
skipping the no.
22
23
skipping the no.


In [3]:
# continue implementation in while loop

print("printing nos.")
i=2
while i<25:
    if i%3==0:
        i+=1
        print ("skipping the no.")
        continue
    print(i)
    i+=1

printing nos.
2
skipping the no.
4
5
skipping the no.
7
8
skipping the no.
10
11
skipping the no.
13
14
skipping the no.
16
17
skipping the no.
19
20
skipping the no.
22
23
skipping the no.


In [11]:
# break implementation in for loop

print("printing nos.")
for i in range(1,101):
    if i%10==0:
        print ("skipping the no.")
        break
    print(i)
print("end")

printing nos.
1
2
3
4
5
6
7
8
9
skipping the no.
end


In [12]:
# break implementation in while loop

i=2
while i<101:
    if i%10==0:
        i+=1
        break
    print(i)
    i+=1
print("End")

2
3
4
5
6
7
8
9
End


In [13]:
# Reversing a Table

a=int(input("Enter any no."))
for i in range(10,0,-1):
    print(a,"*",i,"=",a*i)


Enter any no.12
12 * 10 = 120
12 * 9 = 108
12 * 8 = 96
12 * 7 = 84
12 * 6 = 72
12 * 5 = 60
12 * 4 = 48
12 * 3 = 36
12 * 2 = 24
12 * 1 = 12


In [4]:
# Printing Patterns

a=int(input("Enter any no."))

for i in range(a,0,-1):
    print(i*"*")
    


Enter any no.5
*****
****
***
**
*


In [6]:
# Printing Patterns
a=int(input("Enter any no."))

for i in range(1,a+1):
    print(i*"*")

Enter any no.5
*
**
***
****
*****


In [1]:
# printing Patterns
a=int(input())
for i in range(a,0,-1):
    print((a-i)*" "+i*"* ")
for i in range(2,a+1):
    print((a-i)*" " + i*"* ")

5
* * * * * 
 * * * * 
  * * * 
   * * 
    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [8]:
# printing Patterns
a=int(input())
for i in range(1,a+1): 
    print(i*"*")
for i in range(a-1,0,-1):
    print(i*"*")

5
*
**
***
****
*****
****
***
**
*


In [9]:
# printing Patterns
a=int(input())
for i in range(0,a):
    print((a-i)*" " + (2*i+1)*"*")


4
    *
   ***
  *****
 *******


In [9]:
# printing Patterns
a=int(input())
for i in range(a,0,-1):
    print((a-i)*" " + (2*i+1)*"*")


5
***********
 *********
  *******
   *****
    ***


In [12]:
# To input a string and count the no. of alphabets and nos,

countA =0
countN =0
str = input("Enter the string  ")
nstr =""
for i in str:
    if (i>="A" and i<="Z")or(i>="a" and i<="z"):
        nstr += i
print("Alphabets = ",len(nstr))
print("Numbers = ",len(str)-len(nstr))

Enter the string  Har00ita4
Alphabets =  6
Numbers =  3


In [11]:
# Convert string to upper case

str1 = input("Enter the string  ")
print(str1.upper())

Enter the string  Har00ita4
HAR00ITA4


In [27]:
# Change every letter of string to its next letter

str1 = input("Enter the String  ")
nstr=""
stra= "ABCDEFGHIJKLMNOPQRSTUWXYZ"
strA= "abcdefghijklmnopqrstuvwxyz"

for i in str1:
    if i in strA:
        nstr += strA[strA.index(i)+1]
    elif i in stra:
        nstr += stra[stra.index(i)+1]
    else:
        print("Enter a Valid String")
print(nstr)


Enter the String  ydgfyag
zehgzbh


In [28]:
# WAP to change a hyphen separated string to whitespace separated string

str1 = input("Enter the String  ")
nstr=""

for i in str1:
    if i=="-":
        nstr += " "
    else:
        nstr += str1[str1.index(i)]
print(nstr)


Enter the String  my-name-is-harhita
my name is harhita


In [7]:
# List Fuction Implementation

l1=[1,2,3]
l2=[4,5]
l1.extend(l2)
print(l1)
print(l1[2])
l2=[]
type(l2)

[1, 2, 3, 4, 5]
3


list

In [1]:
# WAP to check the frequency of nos. in list

n=int(input("no. of entries to be in list : "))
print("Enter the values in list")
l1=[]
l2=[]

for x in range(0,n):
    l=int(input())
    if l>10:
        print("INVALID DATA")
    else :
        l1.append(l)
    
for y in range(0,10) :
    count = 0
    for z in l1:
        if y==z:
            count+=1
    l2.append(count)
    
print(l1)
print(l2)

no. of entries to be in list3
Enter the values in list
4
5
4
[4, 5, 4]
[0, 0, 0, 0, 2, 1, 0, 0, 0, 0]


In [13]:
# Write a program that accepts a sequence of whitespace separated words as input and prints the words after
#removing all duplicate words and sorting them alphanumerically.
'''Suppose the following input is supplied to the program:
hello world and practice makes perfect and hello world again
Then, the output should be:
again and hello makes perfect practice world'''

n=input("Enter the sequence ")
l1 = n.split(" ")
l1.sort()
l2 = []

for x in l1:
    if x not in l2:
        l2.append(x)
        
print(l2)

Enter the sequence hello world and practice makes perfect and hello world again
['again', 'and', 'hello', 'makes', 'perfect', 'practice', 'world']


In [27]:
# Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.
'''Example:
0100,0011,1010,1001
Then the output should be:
1010
Notes: Assume the data is input by console.
'''
n=input("Enter the sequence ")
l1 = n.split(",")

for i in l1:
    x1 = int(i[0])
    x2 = int(i[1])
    x3 = int(i[2])
    x4 = int(i[3])
    x = ((x1*8)+(x2*4)+(x3*2)+(x4))
    
    if x%5==0:
        print(i)
        

Enter the sequence 1001,1010,0101,1100
1
1010
0101


In [28]:
# You are required to write a program to sort the (name, age, height) tuples by ascending order where name is string, age and height are numbers. The tuples are input by console. The sort criteria is:
'''1: Sort based on name;
2: Then sort based on age;
3: Then sort by score.
The priority is that name > age > score.
If the following tuples are given as input to the program:
Tom,19,80
John,20,90
Jony,17,91
Jony,17,93
Json,21,85
Then, the output of the program should be:
[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.
We use itemgetter to enable multiple sort keys.'''

n= int(input("Enter the no. of Entries : "))
l=[]
for i in range(n):
    x=(input("name= "),input("age= "),input("score= "))
    l.append(x)
    
l.sort()

print(l)

Enter the no. of Entries : 5
name= tom
age= 19
score= 80
name= John
age= 20
score= 19
name= Jony
age= 17,91
score= Jony
name= 17
age= 93
score= 98
name= json
age= 21
score= 56
[('17', '93', '98'), ('John', '20', '19'), ('Jony', '17,91', 'Jony'), ('json', '21', '56'), ('tom', '19', '80')]


In [1]:
# Concatenation of Strings

str1 = input(" Enter your first name : ")
str2 = input(" Enter your last name : ")

print(str1+str2)

 Enter your first name : Vaishnavi 
 Enter your last name : Kumari
Vaishnavi Kumari


In [4]:
# List functions Implementation


x= int(input("Enter the no. of inputs in list : "))
l1 = [x  for x in input().split(",")]

print(len(l1))
print(l1[0])

y = input("Enter any no. : ")
l1.append(y)
print (l1)
print(l1[-len(l1)])

l1.remove(l1[0])
print(l1)
l1.reverse()
print(l1)
l1.sort()
print(l1)


Enter the no. of inputs in list : 7
45,67,98,31,64,09,83
7
45
Enter any no. : 54
['45', '67', '98', '31', '64', '09', '83', '54']
45
['67', '98', '31', '64', '09', '83', '54']
['54', '83', '09', '64', '31', '98', '67']
['09', '31', '54', '64', '67', '83', '98']


In [6]:

l1=[23,45,98,87]
l2 = [67,85]
print(l1+l2)

[23, 45, 98, 87, 67, 85]


In [18]:
# Dictionary Implementation

city = dict([('Mumbai','Maharastra'),('Delhi','Delhi'),('Chennai','Tamil Naidu'),('Kolkata','West Bengal')])
print(city)
city.update([('Indore','Madhya Pradesh')])
print(city.values())
city.items()

{'Mumbai': 'Maharastra', 'Delhi': 'Delhi', 'Chennai': 'Tamil Naidu', 'Kolkata': 'West Bengal'}
dict_values(['Maharastra', 'Delhi', 'Tamil Naidu', 'West Bengal', 'Madhya Pradesh'])


dict_items([('Mumbai', 'Maharastra'), ('Delhi', 'Delhi'), ('Chennai', 'Tamil Naidu'), ('Kolkata', 'West Bengal'), ('Indore', 'Madhya Pradesh')])

In [21]:
l1=[1,2,3,4,5,6]
l1[1:5:2]



[2, 4]

In [20]:
city.pop('Mumbai')
city.popitem()

('Indore', 'Madhya Pradesh')

In [48]:
tuple1 = (1,2,3,4,5,6,7)
print(tuple1)
    
len(tuple1)
2*tuple1
x1,x2,x3,x4,x5,x6,x7 = tuple1
print(x1)
print(x2)
tuple1[2:5]
 
y=(9,)

tuple2 = tuple1 + y

print(tuple2)


(1, 2, 3, 4, 5, 6, 7)
1
2
(1, 2, 3, 4, 5, 6, 7, 9)


In [1]:
# Game : Stone,Paper,Scissor

from random import random

def RPC(b):
    a = random()
    if (a<=0.33):
        if(b==1):
            print("Rock,Rock")
            print("Draw")
        elif(b==2):
            print("Rock,Paper")
            print(" You Win ")
        else:
            print("Rock,Scissor")
            print("You Lose")
    elif (a<=0.66):
        if(b==2):
            print("Paper,Paper")
            print("Draw")
        elif(b==3):
            print("Paper,Scissor")
            print(" You Win ")
        else:
            print("Paper,Rock") 
            print("You Lose")
    else :
        if(b==3):
            print("Scissor,Scissor")
            print("Draw")
        elif(b==1):
            print("Scissor,Rock")
            print(" You Win ")
        else:
            print("Scissor,Paper")
            print("You Lose")
            
c=int(input("Enter the no. you want to play : "))

for x in range(c):
    print(""""Enter
    1 for Rock
    2 for Paper
    3 for Scissor""")
    b=int(input())
    RPC(b)

Enter the no. you want to play : 5
"Enter
    1 for Rock
    2 for Paper
    3 for Scissor
3
Rock,Scissor
You Lose
"Enter
    1 for Rock
    2 for Paper
    3 for Scissor
2
Paper,Paper
Draw
"Enter
    1 for Rock
    2 for Paper
    3 for Scissor
2
Rock,Paper
 You Win 
"Enter
    1 for Rock
    2 for Paper
    3 for Scissor
1
Paper,Rock
You Lose
"Enter
    1 for Rock
    2 for Paper
    3 for Scissor
3
Rock,Scissor
You Lose


In [3]:
# Library :NUMPY

import numpy as np

a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
a.ndim

1

In [6]:
a.shape

(3,)

In [7]:
b.dtype

dtype('float64')

In [8]:
a.itemsize

4

In [9]:
a.nbytes

12

In [10]:
a.size

3

In [11]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [12]:
t=a

In [13]:
t[0,0]=10

In [14]:
a

array([[10,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [15]:
# get a specific elements
a[1,5]

13

In [16]:
# get a specific row
a[0,:]

array([10,  2,  3,  4,  5,  6,  7])

In [17]:
# Get a specific col
a[:,2]

array([ 3, 10])

In [18]:
# Getting a Little more fancy [start index: endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [19]:
a[1,5] = 20

In [20]:
a[:,2]=[1,2]
print(a)

[[10  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [21]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
# get a specific element (work out side in)
b[0,1,1]

4

In [23]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [24]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# All 1s matrix
np.ones((4,4,2),dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [26]:
# Any other no.
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [27]:
#Any other no.(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [28]:
# Random decimal nos.
np.random.rand(4,2)

array([[0.47080849, 0.98299602],
       [0.1766759 , 0.31896063],
       [0.31829992, 0.47438801],
       [0.98157223, 0.53149983]])

In [29]:
# Random Integer values

np.random.randint(-4,8,size=(3,3))

array([[ 2,  5,  2],
       [ 7, -4, -3],
       [-3,  6, -2]])

In [30]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [32]:

output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1] =z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
a= np.array([1,2,3,4])
b=a.copy()
b[0]=100
print(a)


[1 2 3 4]


In [34]:
a+2

array([3, 4, 5, 6])

In [35]:
a-2

array([-1,  0,  1,  2])

In [36]:
a*2

array([2, 4, 6, 8])

In [37]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [38]:
b= np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [39]:
print(a**2)

[ 1  4  9 16]


In [40]:
# Take a sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [41]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [42]:
# Find the Determinant
c= np.identity(3)
np.linalg.det(c)

1.0

In [43]:
## Reference docs (https://docs.spicy.org.doc/numpy/reference./routines.linalg.html)

# Determinant 
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...


In [44]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.min(stats)

1

In [46]:
np.max(stats,axis=1)

array([3, 6])

In [47]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [48]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
#Horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [52]:
h = range(10)

In [55]:
h = list(h)

In [56]:
h

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [64]:
def double(x):
    return 2*x

In [68]:
j= lambda x,y: x+y 

In [69]:
j(9,8)

17

In [73]:
a=123456789 
b= 1.23456789* 10**8

In [74]:
a

123456789

In [75]:
b

123456788.99999999

In [ ]:
def cd(a,b):
    if(a%b==0 or b%a==0):
        return T
    elif (a>b):
        return cd(a,b%a)
    elif (b>a):
        return cd(b,a%b)
    else:
        return F
    
    
print(cd(9,6))