In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3],dtype = 'int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,9.2,6.3],[4.2,0.6,5.3]])
print(b)

[[9.  9.2 6.3]
 [4.2 0.6 5.3]]


In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
a.dtype

dtype('int32')

In [11]:
b.dtype

dtype('float64')

In [12]:
a.itemsize

4

In [13]:
a.nbytes

12

In [14]:
b.nbytes

48

In [15]:
b.itemsize

8

In [16]:
a.size

3

In [17]:
b.size

6

In [18]:
b[1,2]

5.3

In [20]:
b[0,:]

array([9. , 9.2, 6.3])

In [21]:
b[:,0]

array([9. , 4.2])